### PR TITLE
Pull for Sapper and Sectopod medal. some other corrections.

### PR DESCRIPTION
**Pull request by IvanDogovich**
Merged SAPPER and SECTOPOD_KILL medals in.  Corrected names and numbers in UFOPedia section.

### CODE REVIEW

**Comment by Shoes01** [comment]
Great stuff :) Here are some changes I've made:

I've renamed ribbon 136 to 135, and renamed 135 to 199. I removed the "placeholderribbon" from the name because I think the source code would get confused by it. I then made the corresponding changes in the rest of the ruleset.

Also, in the alpha_release branch, I've moved some of the strings into the language file, so you'll notice the lines 359 - 399 I've removed entirely, as well as the same lines in the other language.

**Comment by IvanDogovich** [comment]
Ah! I get it!  I wondered where those otherlines had gone to!  I was
testing that ruleset stand alone, and it was giving me a lot of STR s and I
couldn't figure out why you had removed them.    Have you considered
submitting this to the transifex site for more translation work?  ie to
bring fr it and ru up to snuff?

Cheers, Ivan :D

**Comment by IvanDogovich** [comment]
Just curious... how does the 99 and medal 199 name thing work?  I thought
that the sprite numbers were sequential and therefore wouldn't find the
"99th" image

**Comment by Shoes01** [comment]
I am trying to find where I coded the "fetch sprite" code, and I can't seem to find it ;p You're right though, the 99 might break things due to being out of sequence. I will chance it to 00 and chance 00's sprite to 36 or whatever we're at now. I'll also add the other commendations I worked on, and give them the appropriate placeholder art names and values.

**Pull request merged**
