### PR TITLE
Update to work with recent nightly (2015-05-22)

### PR DESCRIPTION
**Pull request by fudgedragon**
Merged latest nightly back into alpha_release and resolved lingering preventing compilation with visual studio.

Also reogranised resources/ruleset folder structure and introduced simple metadata.yml to match changes to mods in nightly builds

### CODE REVIEW

**Comment by IvanDogovich** [comment]
Dude. Wow.  Thanks!

**Comment by Shoes01** [comment]
This looks great! I hope to pull it in tonight. Thanks!

**Comment by fudgedragon** [comment]
Heh, no problem. I went to the trouble of doing the merge for myself, seemed a shame not to let anyone else benefit.

**Comment by Shoes01** [comment]
I did things weird in regards to github, but I've merged and updated the download link with your work! I'll have github up to date soon enough.

**Pull request merged**
